{% set version = "3.9.4" %}

package:
  name: easybuild-framework
  version: {{ version }}

source:
  fn: easybuild-framework-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/easybuild-framework/easybuild-framework-{{ version }}.tar.gz
  sha256: 3a924da6cc3c50087f8c24e5d5810236750bdd4812e59866827965f19b01c8de

build:
  number: 0
  skip: True  # [win or py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pyyaml
    - coloredlogs
    - humanfriendly
    - vsc-install >=0.9.19
    - vsc-base >=2.5.4

test:
  imports:
    - easybuild
    - easybuild.framework
    - easybuild.framework.easyconfig
    - easybuild.framework.easyconfig.format
    - easybuild.toolchains
    - easybuild.toolchains.compiler
    - easybuild.toolchains.fft
    - easybuild.toolchains.linalg
    - easybuild.toolchains.mpi
    - easybuild.tools
    - easybuild.tools.deprecated
    - easybuild.tools.job
    - easybuild.tools.module_naming_scheme
    - easybuild.tools.package
    - easybuild.tools.package.package_naming_scheme
    - easybuild.tools.repository
    - easybuild.tools.toolchain

about:
  home: http://hpcugent.github.com/easybuild
  license: GPL-2.0
  summary: 'The EasyBuild framework supports the creation of custom framework that implement support for installing particular (groups of) software packages.'
  license_family: GPL2

extra:
  recipe-maintainers:
    - jerowe
    - boegel
