{% set version = "4.2.2" %}

package:
  name: easybuild-framework
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/easybuild-framework/easybuild-framework-{{ version }}.tar.gz
  sha256: 5752a21e991844637547f9106563fdcd6a667b492d3c3a89cd4da6d99a63a85f

build:
  number: 0
  skip: true  # [win or py3k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pyyaml
    - coloredlogs
    - humanfriendly
    - vsc-install >=0.9.19
    - vsc-base >=2.5.4

test:
  imports:
    - easybuild
    - easybuild.framework
    - easybuild.framework.easyconfig
    - easybuild.framework.easyconfig.format
    - easybuild.toolchains
    - easybuild.toolchains.compiler
    - easybuild.toolchains.fft
    - easybuild.toolchains.linalg
    - easybuild.toolchains.mpi
    - easybuild.tools
    - easybuild.tools.deprecated
    - easybuild.tools.job
    - easybuild.tools.module_naming_scheme
    - easybuild.tools.package
    - easybuild.tools.package.package_naming_scheme
    - easybuild.tools.repository
    - easybuild.tools.toolchain

about:
  home: http://hpcugent.github.com/easybuild
  license: GPL-2.0
  license_file: LICENSE
  summary: The EasyBuild framework supports the creation of custom framework that implement support for installing particular (groups of) software packages.
  license_family: GPL2

extra:
  recipe-maintainers:
    - jerowe
    - boegel
