{% set name = "easybuild-framework" %}
{% set version = "4.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5b380a2e3a359f64f06789c390200b922a840f6b10b441e5163696a34bd9bc27

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - archspec
    - gitpython
    - keyring
    - python >=3.5
    - pyyaml

test:
  imports:
    - easybuild
    - easybuild.base
    - easybuild.framework
    - easybuild.framework.easyconfig
    - easybuild.framework.easyconfig.format
    - easybuild.toolchains
    - easybuild.toolchains.compiler
    - easybuild.toolchains.fft
    - easybuild.toolchains.linalg
    - easybuild.toolchains.mpi
    - easybuild.tools
    - easybuild.tools.deprecated
    - easybuild.tools.job
    - easybuild.tools.module_naming_scheme
    - easybuild.tools.package
    - easybuild.tools.package.package_naming_scheme
    - easybuild.tools.repository
    - easybuild.tools.toolchain
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://easybuilders.github.io/easybuild
  summary: The EasyBuild framework supports the creation of custom easyblocks that implement support for installing particular (groups of) software packages.
  license: GPL-2.0-only
  license_family: GPL2
  license_file: LICENSE
  dev_url: https://github.com/easybuilders/easybuild-framework
  doc_url: https://easybuild.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jerowe
    - boegel
    - anthchirp
